### ISSUE TITLE
ic_launcher в aar файле

### ISSUE THREAD

**Issue by demixdn** [cloudpayments/CloudPayments_AndroidCheckout#2]
В aar совершенно не нужны папки с графическими ресурсами, а файл mipmap-anydpi-v26/ic_launcher перебивает иконку приложения. Там вообще должен быть минималистический AndroidManifest. Ни allowBackup, ни icon, ни supportsRtl, ни theme. В же тем самым навязываете контракт разработчику, который он должен выполнять. Но в sdk эти параметры не нужны.

**Comment by a-ignatov-cp** [comment]
Согласен, спасибо за совет, внесли изменения, sdk обновили.
